# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title

# Setup
title:               Joseph Bae
tagline:             'Computer Engineering Student @ The University of Texas at Austin'
description:         ''
url:                 "http://josephbae.me"
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Joseph Bae
  url:               https://twitter.com/joebaebae
  email:             josephbae@utexas.edu

