# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title

# Setup
title:               Joseph Bae
tagline:             'Software Engineer'
description:         ''
url:                 "http://josephbae.me"
baseurl:             ""
paginate:            5
permalink:           /:title

# About/contact
author:
  name:              Joseph Bae
  url:               http://josephbae.me
  email:             josephbae@utexas.edu

