# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.


# Setup
title:               Joseph Bae
tagline:             'A Jekyll theme'
description:         ''
url:                 http://josephbae.me
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

